/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorJuego;
import controlador.InterfaceJuego;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Participante;

/**
 *
 * @author sartre
 */
public class VistaJuego extends javax.swing.JFrame implements InterfaceJuego{

    /**
     * Creates new form VistaJuego
     */
    Participante participante;
    ControladorJuego controlador;
    
    public VistaJuego(Participante p) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.controlador = new ControladorJuego(this);
        this.participante = p;
        this.lblNombre.setText(p.getJugador().getNombre());
        this.lblEspera.setVisible(true);
        this.lblCarta1.setVisible(false);
        this.lblCarta2.setVisible(false);
        this.lblCarta3.setVisible(false);
        this.lblCarta4.setVisible(false);
        this.lblCarta5.setVisible(false);
    }

    public VistaJuego() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();
        lblEspera = new javax.swing.JLabel();
        lblCarta1 = new javax.swing.JLabel();
        lblCarta2 = new javax.swing.JLabel();
        lblCarta3 = new javax.swing.JLabel();
        lblCarta4 = new javax.swing.JLabel();
        lblCarta5 = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        btnPasar = new javax.swing.JButton();
        contenedorParticipantes = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/iconos/minimize.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimizar");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(30, 0, 14, 20);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/iconos/close.png"))); // NOI18N
        lblClose.setToolTipText("Cerrar");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        getContentPane().add(lblClose);
        lblClose.setBounds(10, 0, 20, 20);

        lblNombre.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNombre);
        lblNombre.setBounds(110, 0, 330, 30);

        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        getContentPane().add(lblBarra);
        lblBarra.setBounds(0, 0, 850, 40);

        lblParticipantes.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        lblParticipantes.setForeground(new java.awt.Color(255, 255, 204));
        lblParticipantes.setText("~ Participantes ~");
        lblParticipantes.setToolTipText("");
        getContentPane().add(lblParticipantes);
        lblParticipantes.setBounds(650, 30, 100, 40);

        lblEspera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEspera.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblEspera);
        lblEspera.setBounds(80, 210, 540, 40);

        lblCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/cards/10_of_diamonds.png"))); // NOI18N
        lblCarta1.setText("asdasdasdasdasda");
        getContentPane().add(lblCarta1);
        lblCarta1.setBounds(170, 80, 110, 160);

        lblCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/cards/6_of_clubs.png"))); // NOI18N
        lblCarta2.setText("asdasdasdasdasda");
        getContentPane().add(lblCarta2);
        lblCarta2.setBounds(310, 80, 110, 160);

        lblCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/cards/jack_of_diamonds.png"))); // NOI18N
        lblCarta3.setText("asdasdasdasdasda");
        getContentPane().add(lblCarta3);
        lblCarta3.setBounds(450, 80, 110, 160);

        lblCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/cards/3_of_hearts.png"))); // NOI18N
        lblCarta4.setText("asdasdasdasdasda");
        getContentPane().add(lblCarta4);
        lblCarta4.setBounds(380, 260, 110, 160);

        lblCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/cards/king_of_clubs.png"))); // NOI18N
        lblCarta5.setText("asdasdasdasdasda");
        getContentPane().add(lblCarta5);
        lblCarta5.setBounds(240, 260, 110, 160);

        btnApostar.setBackground(new java.awt.Color(71, 128, 51));
        btnApostar.setForeground(new java.awt.Color(255, 255, 255));
        btnApostar.setText("Apostar");
        getContentPane().add(btnApostar);
        btnApostar.setBounds(380, 460, 180, 32);

        btnPasar.setBackground(new java.awt.Color(162, 52, 52));
        btnPasar.setForeground(new java.awt.Color(255, 255, 255));
        btnPasar.setText("Pasar");
        getContentPane().add(btnPasar);
        btnPasar.setBounds(170, 460, 180, 32);

        contenedorParticipantes.setBackground(new java.awt.Color(51, 51, 51));

        lstParticipantes.setBackground(new java.awt.Color(89, 89, 104));
        lstParticipantes.setSelectionBackground(new java.awt.Color(215, 215, 89));
        lstParticipantes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        contenedorParticipantes.setViewportView(lstParticipantes);

        getContentPane().add(contenedorParticipantes);
        contenedorParticipantes.setBounds(623, 80, 160, 340);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/background/background_table.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-550, -140, 1400, 660);

        setBounds(0, 0, 811, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        confirmarSalida();
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-x1, y-y1);
    }//GEN-LAST:event_lblBarraMouseDragged
    int x1;
    int y1;
    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnPasar;
    private javax.swing.JScrollPane contenedorParticipantes;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblCarta1;
    private javax.swing.JLabel lblCarta2;
    private javax.swing.JLabel lblCarta3;
    private javax.swing.JLabel lblCarta4;
    private javax.swing.JLabel lblCarta5;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEspera;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JList lstParticipantes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "Está seguro que desea salir?", "Advertencia!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(valor == JOptionPane.YES_OPTION){
            // Como se tiene implementado, que cada mano obtiene la lista de
            // participantes activos, podemos hacer que el participante se 
            // cambia el estado y en la proxima mano ya no estará.
            this.participante.salirDelJuego();
            dispose();
        }
    }

    @Override
    public void mostrarEspera(int faltantes) {
        if(faltantes > 1) lblEspera.setText("Juego en espera. Aún faltan " + faltantes + " participantes");
        else lblEspera.setText("Juego en espera. Aún falta " + faltantes + " participante");
        lblEspera.setVisible(true);
    }

    @Override
    public void iniciarJuego() {
        this.lblEspera.setVisible(false);
        this.lblCarta1.setVisible(true);
        this.lblCarta2.setVisible(true);
        this.lblCarta3.setVisible(true);
        this.lblCarta4.setVisible(true);
        this.lblCarta5.setVisible(true);
    }

    @Override
    public void actualizarListaParticipantes(ArrayList<Participante> participantes) {
        this.lstParticipantes.setListData(participantes.toArray());
    }
}
