/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAdmin;
import controlador.InterfaceAdmin;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Juego;
import modelo.Participante;

/**
 *
 * @author sartre
 */
public class VistaAdministrador extends javax.swing.JFrame implements InterfaceAdmin{

    /** 
     * Creates new form VistaJuego
     */
   
    private ControladorAdmin controlador;
    
    
    
    
    public VistaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
       
        
       
       
        this.controlador = new ControladorAdmin(this);
        this.controlador.ActualizarDatos();
        btnDetalle.setVisible(true);
        lblpart.setVisible(false);
        lstParticipantes.setVisible(false);
        contenedorParticipantes.setVisible(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnPozo = new javax.swing.JButton();
        lblParticipantes = new javax.swing.JLabel();
        btnMaximo = new javax.swing.JButton();
        contenedorjuegos = new javax.swing.JScrollPane();
        lstJuegos = new javax.swing.JList();
        lblLuz = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblmax = new javax.swing.JLabel();
        txtluz = new javax.swing.JTextField();
        btnDetalle = new javax.swing.JButton();
        txtMax = new javax.swing.JTextField();
        lblpart = new javax.swing.JLabel();
        contenedorParticipantes = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/iconos/minimize.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimizar");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(30, 0, 14, 20);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/iconos/close.png"))); // NOI18N
        lblClose.setToolTipText("Cerrar");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        getContentPane().add(lblClose);
        lblClose.setBounds(10, 0, 20, 20);

        lblNombre.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNombre);
        lblNombre.setBounds(110, 0, 330, 30);

        btnPozo.setBackground(new java.awt.Color(71, 128, 51));
        btnPozo.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        btnPozo.setForeground(new java.awt.Color(255, 255, 255));
        btnPozo.setText("Actualizar Luz");
        btnPozo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPozoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPozo);
        btnPozo.setBounds(210, 60, 140, 40);

        lblParticipantes.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        lblParticipantes.setForeground(new java.awt.Color(255, 255, 204));
        lblParticipantes.setText("Monitor Partidas");
        lblParticipantes.setToolTipText("");
        getContentPane().add(lblParticipantes);
        lblParticipantes.setBounds(520, 20, 130, 40);

        btnMaximo.setBackground(new java.awt.Color(158, 158, 15));
        btnMaximo.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        btnMaximo.setForeground(new java.awt.Color(255, 255, 255));
        btnMaximo.setText("Actualizar Maximo");
        btnMaximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaximo);
        btnMaximo.setBounds(210, 120, 140, 40);

        contenedorjuegos.setBackground(new java.awt.Color(51, 51, 51));

        lstJuegos.setBackground(new java.awt.Color(0, 0, 0));
        lstJuegos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lstJuegos.setForeground(new java.awt.Color(255, 255, 255));
        lstJuegos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstJuegos.setSelectionBackground(new java.awt.Color(215, 215, 89));
        lstJuegos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        contenedorjuegos.setViewportView(lstJuegos);

        getContentPane().add(contenedorjuegos);
        contenedorjuegos.setBounds(410, 60, 390, 190);

        lblLuz.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLuz.setForeground(new java.awt.Color(255, 255, 255));
        lblLuz.setText("Luz:");
        getContentPane().add(lblLuz);
        lblLuz.setBounds(10, 80, 30, 20);

        btnSalir.setBackground(new java.awt.Color(162, 43, 34));
        btnSalir.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(20, 450, 140, 40);

        lblmax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmax.setForeground(new java.awt.Color(255, 255, 255));
        lblmax.setText("Maximo Jugadores:");
        getContentPane().add(lblmax);
        lblmax.setBounds(10, 130, 140, 19);

        txtluz.setBackground(new java.awt.Color(0, 0, 0));
        txtluz.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtluz.setForeground(new java.awt.Color(255, 255, 255));
        txtluz.setText("$$$");
        txtluz.setToolTipText("");
        txtluz.setBorder(null);
        getContentPane().add(txtluz);
        txtluz.setBounds(50, 80, 50, 20);

        btnDetalle.setBackground(new java.awt.Color(0, 153, 153));
        btnDetalle.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        btnDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalle.setText("Detalle");
        btnDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalle);
        btnDetalle.setBounds(410, 260, 140, 40);

        txtMax.setBackground(new java.awt.Color(0, 0, 0));
        txtMax.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMax.setForeground(new java.awt.Color(255, 255, 255));
        txtMax.setText("0");
        txtMax.setBorder(null);
        getContentPane().add(txtMax);
        txtMax.setBounds(160, 125, 30, 30);

        lblpart.setBackground(new java.awt.Color(0, 0, 0));
        lblpart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblpart.setForeground(new java.awt.Color(255, 255, 255));
        lblpart.setText("Participantes");
        getContentPane().add(lblpart);
        lblpart.setBounds(420, 314, 190, 20);

        lstParticipantes.setBackground(new java.awt.Color(0, 0, 0));
        lstParticipantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lstParticipantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lstParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        lstParticipantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstParticipantes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedorParticipantes.setViewportView(lstParticipantes);

        getContentPane().add(contenedorParticipantes);
        contenedorParticipantes.setBounds(410, 340, 390, 160);

        lblBackground.setBackground(new java.awt.Color(0, 51, 255));
        lblBackground.setForeground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/utilidades/background/background_table.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-200, -150, 1400, 660);

        setBounds(0, 0, 811, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        confirmarSalida();
    }//GEN-LAST:event_lblCloseMousePressed
    int x1;
    int y1;
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        confirmarSalida();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximoActionPerformed
        // TODO add your handling code here:
        controlador.SetearMaximo(Integer.parseInt(this.txtMax.getText()));
        
    }//GEN-LAST:event_btnMaximoActionPerformed

    private void btnPozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPozoActionPerformed
        // TODO add your handling code here:
       
         controlador.SetearLuz(Integer.parseInt(this.txtluz.getText()));
    }//GEN-LAST:event_btnPozoActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
       controlador.listarParticipantes((Juego)lstJuegos.getSelectedValue());
        
       
    }//GEN-LAST:event_btnDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton btnMaximo;
    private javax.swing.JButton btnPozo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane contenedorParticipantes;
    private javax.swing.JScrollPane contenedorjuegos;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblLuz;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblmax;
    private javax.swing.JLabel lblpart;
    private javax.swing.JList lstJuegos;
    private javax.swing.JList lstParticipantes;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtluz;
    // End of variables declaration//GEN-END:variables
 
    
    

    private void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "Está seguro que desea salir?", "Advertencia!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(valor == JOptionPane.YES_OPTION){
            // Como se tiene implementado, que cada mano obtiene la lista de
            // participantes activos, podemos hacer que el participante se 
            // cambia el estado y en la proxima mano ya no estará.
           // controlador.salirDelJuego();
            dispose();
        }
    }
    
    public void listarParticipantes(ArrayList<Participante> participantes){
            lstParticipantes.removeAll();
            lstParticipantes.setListData(participantes.toArray());
            lstParticipantes.setVisible(true);
            lblpart.setVisible(true);
            contenedorParticipantes.setVisible(true);
    }
    
   

    


   
    public void actualizarListaJuegos(ArrayList<Juego> juegos) {
      
        this.lstJuegos.setListData(juegos.toArray());
    }

    
    public void actualizarLuz(int luz) {
        this.txtluz.setText(""+luz);
    }
    
    public void actualizaMax(int max){
    
        this.txtMax.setText(""+max);
    }

    public void mostrarmensaje(String msg){

        JOptionPane.showMessageDialog(this, msg);
    }

   

   
    public void salir() {
        int valor = JOptionPane.showConfirmDialog(this, "Está seguro que desea salir?", "Advertencia!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(valor == JOptionPane.YES_OPTION){
            // Como se tiene implementado, que cada mano obtiene la lista de
            // participantes activos, podemos hacer que el participante se 
            // cambia el estado y en la proxima mano ya no estará.
           // controlador.salirDelJuego();
            dispose();
        }
    }

    

   
}
